var productList =
{
    MOBILE:[
        {"headings":null,"productCode":"MOBMYSITE","productVersion":"1","expirationDate":"","mediaType":"MOBILE","productName":"Mobile My Site","productDescription":"Mobile My Site (Plus, Premium, Ultimate)","productType":"MSMOB","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"3","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"MOBRANKING","productVersion":"1","expirationDate":"","mediaType":"MOBILE","productName":"Mobile Ranking","productDescription":"Defines appearance of Mobile My site product","productType":"RANKMOB","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"3","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""}
    ],
    MULTI:[
        {"headings":null,"productCode":"CITY145","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"City 145 Package summary product","productDescription":"City 145 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"CITY20","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"City 20 Package summary product","productDescription":"City 20 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"CITY249","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"City 249 Package summary product","productDescription":"City 249 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"CITY399","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"City 399 Package summary product","productDescription":"City 399 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"CITY40","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"City 40 Package summary product","productDescription":"City 40 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"CITY65","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"City 65 Package summary product","productDescription":"City 65 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"CITY99","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"City 99 Package summary product","productDescription":"City 99 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"NAT145","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"National 145 Package summary product","productDescription":"National 145 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"NAT249","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"National 249 Package summary product","productDescription":"National 249 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"NAT399","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"National 399 Package summary product","productDescription":"National 399 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"NAT99","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"National 99 Package summary product","productDescription":"National 99 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"PROV145","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Province 145 Package summary product","productDescription":"Province 145 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"PROV249","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Province 249 Package summary product","productDescription":"Province 249 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"PROV399","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Province 399 Package summary product","productDescription":"Province 399 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"PROV40","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Province 40 Package summary product","productDescription":"Province 40 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"PROV65","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Province 65 Package summary product","productDescription":"Province 65 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"PROV99","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Province 99 Package summary product","productDescription":"Province 99 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"REG145","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Region 145 Package summary product","productDescription":"Region 145 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"REG249","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Region 249 Package summary product","productDescription":"Region 249 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"REG399","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Region 399 Package summary product","productDescription":"Region 399 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"REG65","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Region 65 Package summary product","productDescription":"Region 65 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"REG99","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Region 99 Package summary product","productDescription":"Region 99 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA145","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 145 Package summary product","productDescription":"Traffic 145 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA145+","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 145+ Package summary product","productDescription":"Traffic 145+ Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA20","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 20 Package summary product","productDescription":"Traffic 20 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA249","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 249 Package summary product","productDescription":"Traffic 249 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA249+","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 249+ Package summary product","productDescription":"Traffic 249+ Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA399","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 399 Package summary product","productDescription":"Traffic 399 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA399+","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 399+ Package summary product","productDescription":"Traffic 399+ Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA40","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 40 Package summary product","productDescription":"Traffic 40 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA65","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 65 Package summary product","productDescription":"Traffic 65 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA65+","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 65+ Package summary product","productDescription":"Traffic 65+ Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA99","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 99 Package summary product","productDescription":"Traffic 99 Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRA99+","productVersion":"1","expirationDate":"","mediaType":"MULTI","productName":"Traffic 99+ Package summary product","productDescription":"Traffic 99+ Package summary product","productType":"BUNDLE","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""}
    ],
    ONLINE:[
        {"headings":null,"productCode":"BOOKING","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Booking","productDescription":"Booking service","productType":"ADDONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"1","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"BPL","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"BPL Basic Page Plus","productDescription":"BPL Basic Page Plus","productType":"MS","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"BPLRANKING","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"BPL Ranking","productDescription":"BPL Ranking (1, 2, 3)","productType":"RANKONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"DMVIDEO","productVersion":"2","expirationDate":"","mediaType":"ONLINE","productName":"Demo Video","productDescription":"Demo Video accessed from MySite","productType":"ADDONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"1","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"ECOMMERCE","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"E-commerce","productDescription":"Defines level of e-commerce special media product","productType":"ADDONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"3","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"GOOGLEADW","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Google Adword","productDescription":"Google Adword","productType":"GA","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"IAL","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Instant Ad Lite","productDescription":"Instant Ad Lite","productType":"ADDONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"IP","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Interactive Paper","productDescription":"Interactive Paper","productType":"ADDONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"KAO","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Keyed ad online","productDescription":"Keyed (metered) ad for online","productType":"ADDONL","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"MOBILERK","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Mobile presence","productDescription":"Mobile presence product","productType":"RANKONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"3","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"MYSITE","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"My Site","productDescription":"MyPage, MySite and MySitePlus","productType":"MS","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"3","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"RANKING","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Ranking","productDescription":"Defines appearance of My site product","productType":"RANKONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"3","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"RANKINGUP","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Ranking Upsell","productDescription":"Ranking Upsell","productType":"RANKONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"3","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"SVIDEO","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Standalone video","productDescription":"Stanalone video to deliver to customer","productType":"ADDONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"VIDEO","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Video","productDescription":"Video accessed from MySite","productType":"ADDONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"WEBCARE","productVersion":"1","expirationDate":"","mediaType":"ONLINE","productName":"Webcare","productDescription":"Webcare service","productType":"ADDONL","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"1","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""}
    ],
    PRINT:[
        {"headings":null,"productCode":"WPINCOLUMN","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Incolumn ad for WP","productDescription":"Incolumn advert for White Pages Print (1L, 3L, 5L, 11L, 11LL, 15L, 15LL)","productType":"INN","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"WPINCREA","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Creative Inner column ad for WP","productDescription":"Creative Inner column advert for White Pages Print (1QCI)","productType":"CRINN","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"WPKAP","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Metered ad for WP","productDescription":"Metered ad for White Pages Print","productType":"ADDPR","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"WPLISTING","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Listing for WP","productDescription":"Listing for White Pages Print","productType":"LIST","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"WPOUTCREA","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Creative Outer column ad for WP","productDescription":"Creative Outer column advert for White Pages Print (1QC, 2QC, 3QC, 4QCH)","productType":"CROUT","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"YPINCOLUMN","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Incolumn ad for YP","productDescription":"Incolumn advert for Yellow Pages Print (1L, 3L, 5L, 11L, 11LL)","productType":"INN","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"YPINCREA","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Creative Inner column ad for YP","productDescription":"Creative Inner column advert for Yellow Pages Print (1QCI)","productType":"CRINN","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"YPKAP","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Metered ad for YP","productDescription":"Metered ad for Yellow Pages Print","productType":"ADDPR","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"YPLISTING","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Listing for YP","productDescription":"Listing for Yellow Pages Print","productType":"LIST","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"YPOUTCREA","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Creative Outer column ad for YP","productDescription":"Creative Outer column advert for Yellow Pages Print (1QC, 2QC, 3QC, 4QC, 4QCH, 8QC, 16QC, 32QC)","productType":"CROUT","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"YPRESTO","productVersion":"1","expirationDate":"","mediaType":"PRINT","productName":"Creative outer column ad for Resto section of YP","productDescription":"Creative outer column adverts for Resto section of Yellow Pages Print (RG1/2, RG1/2, RG1/3, RG1/4, RKM)","productType":"RES","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""}
    ],
    SERVICE:[
        {"headings":null,"productCode":"COPYWRITE","productVersion":"1","expirationDate":"","mediaType":"SERVICE","productName":"Copywrite service","productDescription":"Copywrite service","productType":"ADDSRV","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"PMODVER","productVersion":"1","expirationDate":"","mediaType":"SERVICE","productName":"Product Model Version","productDescription":"Version - 8/11/2012","productType":"ADDSRV","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"0","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"SHOOTING","productVersion":"1","expirationDate":"","mediaType":"SERVICE","productName":"Photoshoot","productDescription":"Photoshoot service","productType":"ADDSRV","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRAINING","productVersion":"1","expirationDate":"","mediaType":"SERVICE","productName":"Training","productDescription":"Training","productType":"ADDSRV","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""},
        {"headings":null,"productCode":"TRANSLATE","productVersion":"1","expirationDate":"","mediaType":"SERVICE","productName":"Translation(s)","productDescription":"Translation(s)","productType":"ADDSRV","limitInventoryType":"","daysForFulfillment":"0","maxAppearances":"999","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""}
    ],
    SPECIAL:[
        {"headings":null,"productCode":"GPS","productVersion":"1","expirationDate":"","mediaType":"SPECIAL","productName":"GPS","productDescription":"GPS","productType":"GPS","limitInventoryType":"","daysForFulfillment":"7","maxAppearances":"3","agreementReqInd":"Y","editInContentEditor":"","showAppearAttrList":"","productStatus":"","effectiveDate":"","productionDate":""}
    ]
};